// app/routes/backups/page.tsx
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { api } from "@/convex/_generated/api";
import { authClient } from "@/lib/auth-client";
import createBackup from "@/lib/backups/create-backup";
import restoreBackup from "@/lib/backups/restore-backup";
import {
  Authenticated,
  AuthLoading,
  useConvexAuth,
  useMutation,
  useQuery,
} from "convex/react";
import {
  ArchiveRestore,
  ArrowRight,
  Clipboard,
  Copy,
  Delete,
  Trash,
} from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function BackupsPage() {
  const [backupData, setBackupData] = useState("");
  const [inputtedBackupData, setInputtedBackupData] = useState("");
  const [inputtedBackupName, setInputtedBackupName] = useState("");
  const [loading, setLoading] = useState(false);

  const cloudBackups = useQuery(api.backups.getBackups);
  const createCloudBackup = useMutation(api.backups.createBackup);
  const session = authClient.useSession();
  const convexAuth = useConvexAuth();

  useEffect(() => {
    setBackupData(createBackup());
  }, []);

  return (
    <div className="max-w-4xl mx-auto w-full p-4 flex flex-col gap-4">
      <h1 className="text-4xl">Backups</h1>
      <Card>
        <CardHeader>
          <CardTitle>Local Backup</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          Export
          <div className="flex flex-row gap-3">
            <Input disabled={true} value={backupData} />
            <Button
              size="icon"
              onClick={() => {
                navigator.clipboard
                  .writeText(backupData)
                  .then(() => {
                    toast.success("Backup copied to clipboard");
                  })
                  .catch((error) => {
                    toast.error("Failed to copy backup to clipboard");
                  });
              }}
            >
              <Clipboard />
            </Button>
          </div>
          Import
          <div className="flex flex-row gap-3">
            <Input
              value={inputtedBackupData}
              onChange={(e) => setInputtedBackupData(e.target.value)}
            />
            <Button
              disabled={inputtedBackupData.length === 0}
              onClick={() => {
                setLoading(true);
                restoreBackup(inputtedBackupData);
              }}
            >
              Import
            </Button>
          </div>
        </CardContent>
      </Card>

      {session.data?.user &&
      (convexAuth.isLoading || !cloudBackups?.success) ? (
        <>
          <Skeleton className="h-10 w-[150px]" />
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
            <Skeleton className="h-24 w-full rounded-xl" />
            <Skeleton className="h-24 w-full rounded-xl" />
            <Skeleton className="h-24 w-full rounded-xl" />
          </div>
        </>
      ) : (
        <>
          <h2 className="text-2xl">Cloud Backups</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
            <div className="border bg-card rounded-xl p-4 flex flex-col gap-2">
              <h3 className="text-lg">Create Backup</h3>
              <div className="flex flex-row gap-2">
                <Input
                  value={inputtedBackupName}
                  onChange={(e) => setInputtedBackupName(e.target.value)}
                  placeholder="Backup Name"
                />
                <Button
                  size="icon"
                  onClick={async () => {
                    setLoading(true);
                    const result = await createCloudBackup({
                      data: createBackup(),
                      name: inputtedBackupName,
                    });
                    if (result?.success) {
                      toast.success("Backup created");
                      setInputtedBackupName("");
                    } else {
                      toast.error("Failed to create backup");
                    }
                    setLoading(false);
                  }}
                >
                  <ArrowRight />
                </Button>
              </div>
            </div>
            {cloudBackups?.success &&
              cloudBackups?.backups?.map((backup) => (
                <div
                  key={backup._id}
                  className="flex flex-col gap-2 bg-card rounded-xl p-4 border"
                >
                  <h3 className="text-lg">{backup.name}</h3>
                  <div className="grow"></div>
                  <div className="flex flex-row gap-2 justify-end">
                    <Button variant="destructive" size="icon">
                      <Trash />
                    </Button>
                    <Button variant="outline" size="icon">
                      <Copy />
                    </Button>
                    <Button
                      onClick={() => {
                        restoreBackup(backup.data);
                      }}
                    >
                      <ArchiveRestore />
                      Restore
                    </Button>
                  </div>
                </div>
              ))}
          </div>
        </>
      )}
    </div>
  );
}

// src/routes/backups/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import {
		SignedIn,
		SignedOut,
		SignInButton,
		UserButton,
		useClerkContext,
		SignIn,
		SignUp,
		UserProfile
	} from 'svelte-clerk/client';
	const ctx = useClerkContext();

	let sessionToken = $state('');

	import dayjs from 'dayjs';

	$effect(() => {
		getToken().then((token) => {
			sessionToken = token;
		});
	});

	import { useConvexClient, useQuery } from 'convex-svelte';
	import { api } from '$lib/../convex/_generated/api.js';
	import Button, { buttonVariants } from '$lib/components/ui/button/button.svelte';
	import * as Card from '$lib/components/ui/card/index.js';
	import Input from '$lib/components/ui/input/input.svelte';
	import LoaderCircle from '@lucide/svelte/icons/loader-circle';
	import * as AlertDialog from '$lib/components/ui/alert-dialog/index.js';
	import { toast } from 'svelte-sonner';
	import Backup from './backup.svelte';
	import createBackup from '$lib/createBackup';
	import restoreBackup from '$lib/restoreBackup';
	import Clipboard from '@lucide/svelte/icons/clipboard';
	import Info from '@lucide/svelte/icons/info';
	import * as Alert from '$lib/components/ui/alert/index.js';

	let query = $state(useQuery(api.backups.get, { jwt: '' }));
	const client = useConvexClient();
	let enteredBackupName = $state('');
	let loading = $state(false);

	let backupData = $state('');
	let inputtedBackupData = $state('');

	onMount(() => {
		backupData = createBackup();
	});

	$effect(() => {
		query = useQuery(api.backups.get, { jwt: sessionToken });
	});

	async function getToken() {
		const token = await ctx.session?.getToken();
		if (!token) {
			if (ctx.session) {
				toast.error('Something went wrong');
			}
			return '';
		}
		return token;
	}

	function setLoading(value: boolean) {
		loading = value;
	}
</script>

<div class="mx-auto flex w-full max-w-3xl flex-col gap-3 p-3">
	<AlertDialog.Root open={loading}
		><AlertDialog.Content class="flex flex-row gap-3">
			<LoaderCircle class="animate-spin" />
			Loading
		</AlertDialog.Content>
	</AlertDialog.Root>

	<Card.Root>
		<Card.Header><Card.Title>Local Backup</Card.Title></Card.Header>
		<Card.Content class="flex flex-col gap-3">
			Export
			<div class="flex flex-row gap-3">
				<Input disabled={true} value={backupData} />
				<Button
					size="icon"
					onclick={() => {
						navigator.clipboard
							.writeText(backupData)
							.then(() => {
								toast.success('Backup copied to clipboard');
							})
							.catch((error) => {
								toast.error('Failed to copy backup to clipboard');
							});
					}}><Clipboard /></Button
				>
			</div>
			Import
			<div class="flex flex-row gap-3">
				<Input bind:value={inputtedBackupData} />
				<Button
					onclick={() => {
						loading = true;
						restoreBackup(inputtedBackupData);
					}}>Import</Button
				>
			</div>
		</Card.Content>
	</Card.Root>

	<SignedIn>
		<div class="grid w-full grid-cols-1 gap-3 md:grid-cols-2">
			<Card.Root>
				<Card.Header><Card.Title>Create a Backup</Card.Title></Card.Header>
				<Card.Footer class="flex flex-row gap-3">
					<Input placeholder="Backup Name" bind:value={enteredBackupName} />
					<Button
						disabled={!sessionToken}
						onclick={() => {
							loading = true;
							getToken().then((token) => {
								if (enteredBackupName.length > 0) {
									client
										.mutation(api.backups.create, {
											name: enteredBackupName,
											jwt: token,
											data: createBackup()
										})
										.then(() => {
											enteredBackupName = '';
											toast.success('Backup created successfully');
											loading = false;
										});
								}
							});
						}}>Create</Button
					>
				</Card.Footer>
			</Card.Root>
			{#if !query.data}
				<div class="flex items-center justify-center">
					<LoaderCircle class="animate-spin" />
				</div>
			{/if}
			{#each query.data || [] as backup}
				<Backup {backup} {client} {getToken} {setLoading} />
			{/each}
		</div>
	</SignedIn>
	<SignedOut>
		<Alert.Root>
			<Info />
			<Alert.Title>Tip</Alert.Title><Alert.Description
				>Backup to the cloud with an EduTools account.</Alert.Description
			></Alert.Root
		>
	</SignedOut>
</div>
