// app/routes/auth/ott.tsx
import { Spinner } from "@/components/ui/spinner";
import { authClient } from "@/lib/auth-client";
import { useConvexAuth } from "convex/react";
import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router";
import { toast } from "sonner";

export default function Ott() {
  const [searchParams] = useSearchParams();
  const token = searchParams.get("token");
  const redirect = searchParams.get("redirect");
  const auth = useConvexAuth();
  const navigate = useNavigate();

  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState<string>("Loading");

  async function handleAuth() {
    setMessage("Logging in");
    try {
      const result = await authClient.signIn.ott({
        token: token || "",
      });

      if (result.error) {
        setMessage(result.error.message || "");
        setLoading(false);
      } else {
        toast.success("Logged in");
        navigate(new URL(redirect || "").pathname);
      }
    } catch (error) {
      setMessage("Something went wrong");
      setLoading(false);
    }
  }

  useEffect(() => {
    if (!auth.isLoading) handleAuth();
  }, [auth.isLoading]);

  return (
    <div className="w-full h-full flex flex-row gap-2 justify-center items-center p-4">
      {loading && <Spinner />}
      {message}
    </div>
  );
}

// src/routes/ott/+page.svelte
<script lang="ts">
	import { authClient } from '$lib/auth-client';
	import { CircleAlert, LoaderCircle } from '@lucide/svelte';
	import { useConvexAuth } from 'convex/react';
	// import { onMount } from 'svelte';
	import { page } from '$app/state';
	import { onMount, untrack } from 'svelte';
	import { useAuth } from '@mmailaender/convex-better-auth-svelte/svelte';
	import { goto } from '$app/navigation';
	import { toast } from 'svelte-sonner';

	const auth = useAuth();

	let error = $state(false);
	let errorMessage = $state('');

	function explicitEffect(fn: () => void, depsFn: () => any[]) {
		$effect(() => {
			depsFn();
			untrack(fn);
		});
	}

	explicitEffect(
		() => {
			if (!auth.isLoading) {
				if (auth.isAuthenticated) {
					goto(page.url.searchParams.get('redirect') || '/');
					toast.success('Logged in successfully!');
				}

				authClient.signIn
					.ott({
						token: page.url.searchParams.get('token') || ''
					})
					.then((response) => {
						if (response.error) {
							error = true;
							errorMessage = response.error.message;
						}
					})
					.catch(() => {
						error = true;
					});
			}
		},
		() => [auth.isLoading]
	);
</script>

<div class="flex h-full w-full flex-row items-center justify-center gap-2 p-10">
	{#if error}
		<CircleAlert />
		{errorMessage}
	{:else}
		<LoaderCircle class="animate-spin" />
		Logging in...
	{/if}
</div>
