// app/routes/g/play.tsx
import { getGmaeById } from "@/lib/gmaes";
import type { Route } from "./+types/play";
import { data } from "react-router";
import { Button } from "@/components/ui/button";
import {
  AppWindow,
  Bookmark,
  BookmarkCheck,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Fullscreen,
  Keyboard,
  Maximize,
  RefreshCw,
  Scan,
  Share,
  Square,
} from "lucide-react";
import { ButtonGroup } from "@/components/ui/button-group";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { useSidebar } from "@/components/ui/sidebar";
import {
  useExperimentalFeatures,
  useGmaeHistory,
  useSavedGmaes,
} from "@/lib/state";
import { isExperimentalFeaturesEnabled } from "@/lib/experimental-check";

export async function clientLoader({ params }: Route.ActionArgs) {
  if (!params.id) throw data(null, { status: 404 });
  if (!getGmaeById(params.id)) throw data(null, { status: 404 });

  if (!isExperimentalFeaturesEnabled()) {
    throw data(null, { status: 404 });
  }
}

export default function PlayPage(props: Route.ComponentProps) {
  return (
    <>
      <Play key={props.params.id} {...props} />
    </>
  );
}

export function Play({ params }: Route.ComponentProps) {
  const gmae = getGmaeById(params.id);
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const sidebar = useSidebar();
  const [maximized, setMaximized] = useState(false);

  const addToHistory = useGmaeHistory((state) => state.addToHistory);
  const saved = useSavedGmaes((state) => state.saved);
  const toggleSaved = useSavedGmaes((state) => state.toggleSaved);
  const isSaved = gmae?.id ? saved.includes(gmae.id) : false;

  useEffect(() => {
    if (gmae?.id) {
      addToHistory(gmae.id);
    }
  }, [gmae?.id]);

  return (
    <div className="w-full h-full flex flex-col gap-2 bg-sidebar">
      <iframe
        src={gmae?.url}
        ref={iframeRef}
        className="w-full h-full rounded-md fullscreen:rounded-none"
      ></iframe>
      {!maximized ? (
        <div className="flex flex-col md:flex-row gap-2 bg-card md:p-0 p-2">
          <div className="flex flex-col p-2">
            <p className="text-sm text-muted-foreground">{gmae?.category}</p>
            <h1 className="text-4xl font-extrabold tracking-tight">
              {gmae?.name}
            </h1>
            <p className="leading-7">{gmae?.description}</p>
          </div>
          <div className="grow"></div>
          <div className="flex flex-col gap-2 items-end">
            <ButtonGroup>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    size="icon"
                    variant="outline"
                    onClick={() => {
                      iframeRef.current?.focus();
                      toast.success("Focused gmae");
                    }}
                  >
                    <Keyboard />
                    <span className="sr-only">Fix keyboard input</span>
                  </Button>
                </TooltipTrigger>
                <TooltipContent>Fix keyboard input</TooltipContent>
              </Tooltip>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    size="icon"
                    variant="outline"
                    onClick={() => {
                      iframeRef.current?.contentWindow?.location.reload();
                    }}
                  >
                    <RefreshCw />
                    <span className="sr-only">Reload</span>
                  </Button>
                </TooltipTrigger>
                <TooltipContent>Reload</TooltipContent>
              </Tooltip>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    size="icon"
                    variant="outline"
                    onClick={() => {
                      const win = window.open(
                        "",
                        "",
                        "width=500px,height=500px"
                      );

                      let frame = document.createElement("iframe");
                      frame.src = gmae?.url || "";
                      frame.style.width = "100%";
                      frame.style.height = "100%";
                      frame.style.border = "none";
                      win?.document.body.appendChild(frame);
                      if (win) {
                        win.document.body.style.margin = "0";
                        win.document.title = "Google";
                      }
                    }}
                  >
                    <AppWindow />
                    <span className="sr-only">Open in new window</span>
                  </Button>
                </TooltipTrigger>
                <TooltipContent>Open in new window</TooltipContent>
              </Tooltip>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    size="icon"
                    variant="outline"
                    onClick={() => {
                      const win = window.open("");

                      let frame = document.createElement("iframe");
                      frame.src = gmae?.url || "";
                      frame.style.width = "100%";
                      frame.style.height = "100%";
                      frame.style.border = "none";
                      win?.document.body.appendChild(frame);
                      if (win) {
                        win.document.body.style.margin = "0";
                        win.document.title = "Google";
                      }
                    }}
                  >
                    <ExternalLink />
                    <span className="sr-only">Open in new tab</span>
                  </Button>
                </TooltipTrigger>
                <TooltipContent>Open in new tab</TooltipContent>
              </Tooltip>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    size="icon"
                    onClick={() => {
                      sidebar.setOpen(false);
                      setMaximized(true);
                    }}
                    variant="outline"
                  >
                    <ChevronDown />
                    <span className="sr-only">Maximize</span>
                  </Button>
                </TooltipTrigger>
                <TooltipContent>Maximize</TooltipContent>
              </Tooltip>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    size="icon"
                    onClick={() => {
                      iframeRef.current?.requestFullscreen();
                      iframeRef.current?.focus();
                    }}
                  >
                    <Maximize />
                    <span className="sr-only">Fullscreen</span>
                  </Button>
                </TooltipTrigger>
                <TooltipContent>Fullscreen</TooltipContent>
              </Tooltip>
            </ButtonGroup>
            <ButtonGroup>
              <Button
                variant={isSaved ? "default" : "outline"}
                onClick={() => {
                  if (gmae?.id) {
                    toggleSaved(gmae.id);
                  }
                }}
              >
                {isSaved ? <BookmarkCheck /> : <Bookmark />}
                {isSaved ? "Saved" : "Save"}
              </Button>
              <Button
                variant="outline"
                onClick={async () => {
                  const url = new URL(window.location.href);
                  url.searchParams.set("utm_medium", "share");
                  url.searchParams.set("utm_source", "edutools");
                  url.searchParams.set("utm_campaign", "play-page-share");
                  if (!navigator.canShare || !navigator.share) {
                    if (!navigator.clipboard) {
                      toast.error("Failed to share");
                      return;
                    }
                    navigator.clipboard.writeText(url.toString()).then(() => {
                      toast.success("Copied to clipboard");
                    });
                  } else {
                    navigator
                      .share({
                        url: url.toString(),
                      })
                      .catch((error) => {
                        if (error == "AbortError: Share canceled") return;
                        toast.error("Failed to share");
                      });
                  }
                }}
              >
                <Share />
                Share
              </Button>
            </ButtonGroup>
          </div>
        </div>
      ) : (
        <div className="p-2 md:py-0 flex flex-row">
          <h1 className="text-xl">{gmae?.name}</h1>
          <div className="grow"></div>
          <Button
            size="icon"
            variant="ghost"
            onClick={() => {
              if (!sidebar.isMobile) sidebar.setOpen(true);
              setMaximized(false);
            }}
          >
            <ChevronUp />
          </Button>
        </div>
      )}
    </div>
  );
}

// src/lib/components/play.svelte
<script lang="ts">
	let { id } = $props();

	// Framework imports
	import { page } from '$app/state';

	// Components
	import { Button } from '$lib/components/ui/button/index.js';
	import { toast } from 'svelte-sonner';

	// Icons
	import Refresh from 'lucide-svelte/icons/refresh-cw';
	import Fullscreen from 'lucide-svelte/icons/maximize';
	import OpenInNewTab from 'lucide-svelte/icons/external-link';
	import Share from 'lucide-svelte/icons/share';
	import Bookmark from 'lucide-svelte/icons/bookmark';

	// App imports
	import { getGameById } from '$lib/gmaes';
	import { preferencesStore, favoritesStore, historyStore } from '$lib/stores';
	import { onMount } from 'svelte';

	function openNewTab(url: string) {
		url = location.origin + url;
		var openedTab;
		if ($preferencesStore.open === 'tab') {
			openedTab = window.open('', '_blank');
		} else if ($preferencesStore.open === 'window') {
			openedTab = window.open('', '_blank');
		} else {
			$preferencesStore.open = 'tab';
			openNewTab(url);
			return;
		}
		if (!openedTab) return;
		const newDocument = openedTab.document;
		const style = newDocument.createElement('style');
		style.textContent = 'body, html { margin: 0; padding: 0; height: 100%; }';
		newDocument.head.appendChild(style);
		const iframe = newDocument.createElement('iframe');
		iframe.src = url;
		iframe.style.cssText = 'width: 100%; height: 100%; border: none;';
		newDocument.body.appendChild(iframe);
	}

	const gmaedata = $derived(getGameById(id));

	onMount(() => {
		let history = $historyStore;
		if (history.includes(id)) {
			history = history.filter((historyId) => historyId !== id);
		}

		history.push(id);

		historyStore.set(history);
	});
</script>

<div class="flex h-full w-full flex-row gap-3 p-3">
	<iframe src={gmaedata?.url} frameborder="0" class="flex-grow rounded" title={gmaedata?.name}
	></iframe>

	<div class="flex h-full w-72 flex-col">
		<h1 class="text-4xl font-bold">{gmaedata?.name}</h1>
		<p class="text-xl">{gmaedata?.description}</p>
		<div class="flex-grow"></div>
		<div class="flex flex-col gap-3">
			<Button
				variant="outline"
				onclick={() => {
					const iframe = document.querySelector('iframe');
					if (iframe && gmaedata?.url) {
						iframe.src = gmaedata.url;
					}
				}}
			>
				<Refresh class="h-6 w-6" />
				Reload
			</Button>
			<Button
				variant="outline"
				onclick={() => {
					document.querySelector('iframe')?.requestFullscreen();
				}}
			>
				<Fullscreen class="h-6 w-6" />
				Fullscreen
			</Button>
			<Button
				variant="outline"
				onclick={() => {
					if (gmaedata?.url) openNewTab(gmaedata.url);
				}}
			>
				<OpenInNewTab class="h-6 w-6" />
				New tab
			</Button>
			<Button
				variant="outline"
				onclick={() => {
					if (navigator.share) {
						navigator
							.share({
								text: window.location.href
							})
							.catch(() => {
								navigator.clipboard.writeText(window.location.href);
								toast.error('Failed to share link, copied to clipboard instead.');
							});
					} else {
						navigator.clipboard.writeText(window.location.href);
						toast.error('Failed to share link, copied to clipboard instead.');
					}
				}}
			>
				<Share class="h-6 w-6" />
				Share
			</Button>
			<Button
				variant="outline"
				onclick={() => {
					if (gmaedata?.id) {
						if ($favoritesStore.includes(gmaedata.id)) {
							$favoritesStore = $favoritesStore.filter((id) => id !== gmaedata.id);
						} else {
							$favoritesStore = [...$favoritesStore, gmaedata.id];
						}
					}
				}}
			>
				{#if gmaedata?.id && $favoritesStore.includes(gmaedata.id)}
					<Bookmark class="h-6 w-6 text-red-400" />
					Saved
				{:else}
					<Bookmark class="h-6 w-6" />
					Save
				{/if}
			</Button>
		</div>
	</div>
</div>
